### ISSUE TITLE
Something is wrong or needs better Readme

### ISSUE THREAD

**Issue by spirulin** [H4xton/TikTok-Reportation-Bot#2]
```
Video ID >7011528913981574406
Video Link >https://www.tiktok.com/@_georgieva02/video/7011528913981574406
Traceback (most recent call last):
  File "Bot.py", line 60, in <module>
    videolink = input("Video Link >")
  File "<string>", line 1
    https://www.tiktok.com/@_georgieva02/video/7011528913981574406
         ^
SyntaxError: invalid syntax
```

Am I doing something wrong?

**Comment by H4xton** [comment]
Im not gonna help u here since there is nothing wrong with this video at all Use the tool for good.

**Comment by spirulin** [comment]
It was just for example. I have the same vision as you for what it should be.

**Comment by spirulin** [comment]
> Im not gonna help u here since there is nothing wrong with this video at all Use the tool for good.

It was just for example. I have the same vision as you for what it should be.
